# Generated by Django 4.0.2 on 2024-10-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='task_assign',
        ),
    ]
